displayName=Clog Casino
author=nreaver1
support=https://github.com/nreaver1/osrs-luck-tracker-plugin
description=Shows how spooned or dry you were for each collection log drop, on the Clog Casino website
tags=collection log,clog,luck,drop rate,spooned,dry,statistics
plugins=com.osrslucktracker.LuckTrackerPlugin
build=standard
