displayName=Collection Log Luck Tracker
author=nreaver1
support=https://github.com/nreaver1/osrs-luck-tracker-plugin
description=Reports how spooned or dry you are for new collection log drops to the Luck Tracker website
tags=collection log,luck,drop rate,spooned,dry,statistics
plugins=com.osrslucktracker.LuckTrackerPlugin
build=standard
